serverPort = 8080
mode = "local"
host = "http://120.26.42.156:9933"
chainId = 90
startHeight = 0
isReStartScan= true

[database.local]
type= "mysql"
mode= "release"
name= "eth_blockchain"
url= "127.0.0.1:3306"
user= "root"
password= "123456"

[log]
level = "info"
formatter = ""
outfile = "logs/info.log"
errfile = "logs/err.log"
sqlfile = "logs/sql.log"
