mode = "test"
#host = "http://124.71.12.16:9933"
host = "http://119.23.219.232:9933"
#chainId = 9090
chainId = 42
startHeight = 95203

[database]
type= "mysql"
mode= "release"
name= ""
url= "127.0.0.1:3306"
user= "root"
password= "123456"

[log]
level = "info"
formatter = ""
outfile = "logs/info.log"
errfile = "logs/err.log"
