mode = "test"
#host = "http://124.71.12.16:9933"
host = "http://119.23.219.232:9933"
#chainId = 9090
chainId = 42
startHeight = 95203

[database]
type= "mysql"
mode= "release"
name= ""
url= ""
user= ""
password= ""

[log]
level = "info"
formatter = ""
outfile = "info.log"
errfile = "err.log"
