mode = "test"
#host = "http://124.71.12.16:9933"
host = "http://119.23.219.232:9933"
#chainId = 9090
chainId = 42
startHeight = 95203
isReStartScan= true

[database]
type= "mysql"
mode= "release"
name= "eth_blockchain"
url= "52.83.177.130:3306"
user= "root"
password= "jlw999000"

[log]
level = "info"
formatter = ""
outfile = "logs/info.log"
errfile = "logs/err.log"
